export declare type Key = AlphabetKey | MiscKey | ModifierKey;
export declare type AlphabetKey =
  | 'a'
  | 'b'
  | 'c'
  | 'd'
  | 'e'
  | 'f'
  | 'g'
  | 'h'
  | 'i'
  | 'j'
  | 'k'
  | 'l'
  | 'm'
  | 'n'
  | 'o'
  | 'p'
  | 'q'
  | 'r'
  | 's'
  | 't'
  | 'u'
  | 'v'
  | 'w'
  | 'x'
  | 'y'
  | 'z';
export declare type MiscKey = '?' | '+' | '-' | 'Enter' | 'Tab' | 'Escape';
export declare type ModifierKey = 'Shift' | 'Control' | 'Meta' | 'Alt';
